# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#
# Development Settings
#
# Run during the 'gulp' command, overwrites _config.yml

url: http://localhost:3000

# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true

# Disables the more accurate related posts for faster generating of the site
lsi: false

# Only make the last 10 posts so generating isn't slow
limit_posts: 10

